logging:
  level:
    root: INFO
spring:
  datasource:
    username: root
    password: huyhuyhuy1312
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:29092
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false